In [1]:
import torch
x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


In [2]:
print(x+1)

tensor([2, 3, 4])


In [3]:
matrix = torch.tensor([
    [1,2],
    [3,4]
])

print(matrix)

tensor([[1, 2],
        [3, 4]])


In [4]:
import torch.nn as nn

model = nn.Linear(2,1)

print(model)

Linear(in_features=2, out_features=1, bias=True)
